ENT.Base 			= "npc_vj_human_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "SPV3 Humanoid Base"
ENT.Author 			= "SgtFlex"
ENT.Purpose 		= "To spawn units."
ENT.Instructions	= "Click on it to spawn it."
ENT.Category		= "Halo CE SPV3"