ENT.Base 			= "spv3_snpc_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Brute Major"
ENT.Author 			= "Mayhem"
ENT.Contact 		= "http://vrejgaming.webs.com/"
ENT.Purpose 		= "Let it eat you."
ENT.Instructions	= "Click on it to spawn it."
ENT.Category		= "Halo CE SPV3"