ENT.Base 			= "npc_vj_halo_flood_spv3_elite"
ENT.Type 			= "ai"
ENT.PrintName 		= "Flood Elite"
ENT.Author 			= "Mayhem"
ENT.Contact 		= "http://vrejgaming.webs.com/"
ENT.Purpose 		= "Let it eat you."
ENT.Instructions	= "Click on it to spawn it."
ENT.Category		= "Halo CE SPV3"