ENT.Base 			= "dropship_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Pelican (unarmed)"
ENT.Author 			= "SgtFlex"
ENT.Contact 		= "http://vrejgaming.webs.com/"
ENT.Purpose 		= "Let it eat you."
ENT.Instructions	= "Click on it to spawn it."
ENT.Category		= "Halo CE SPV3"