ENT.Base 			= "dropship_halo_unsc_spv3_pelican"
ENT.Type 			= "ai"
ENT.PrintName 		= "Pelican (armed)"
ENT.Author 			= "SgtFlex"
ENT.Contact 		= "http://vrejgaming.webs.com/"
ENT.Purpose 		= "Spawns units."
ENT.Instructions	= "Click on it to spawn it."
ENT.Category		= "Halo CE SPV3"